export const sampleResponse = {
  "BrokerageHistoryOut": [{
    "Action": "Credit Interest",
    "Amount": "$0.05",
    "Description": "SCHWAB1 INT 05/27-06/28",
    "FeesAndCommission": "",
    "Price": "",
    "Quantity": "",
    "Symbol": null,
    "PresentationSymbol": null,
    "TransactionDate": "06/29/2020",
    "EffectiveDate": "06/29/2020",
    "IsCharitableGiving": false,
    "ShowDetailsLink": false,
    "ShowS1CheckDetailsLink": false,
    "ShowWireDetailsLink": false,
    "ShowDepositsLink": false,
    "OverlaySubtitle": " - SCHWAB1 INT 05/27-06/28",
    "AccruedInterest": null,
    "PrimeBroker": null,
    "Commission": null,
    "CusipId": null,
    "ExchProcFee": null,
    "OrderHandlingFee": null,
    "Other": null,
    "Principal": null,
    "RedemptionFee": null,
    "SecurityNumber": null,
    "SettleDate": null,
    "StateTaxes": null,
    "Total": null,
    "TradeDate": null,
    "WithHoldingTaxes": null,
    "TranPrimeBrkrAm": null,
    "RowIndex": 0,
    "SourceCode": "S1INT",
    "AccountNumber": "1234",
    "CheckNumber": "",
    "CheckDate": null,
    "DepositSeqId": "1",
    "AmountVerify": null,
  }, {
    "Action": "Buy",
    "Amount": "-$400.00",
    "Description": "MATERIALISE NV FSPONSORED ADR 1 ADR REPS 1 ORD SHS",
    "FeesAndCommission": "",
    "Price": "$20.00",
    "Quantity": "20",
    "Symbol": "MTLS",
    "PresentationSymbol": "MTLS",
    "TransactionDate": "05/15/2020",
    "EffectiveDate": "05/15/2020",
    "IsCharitableGiving": false,
    "ShowDetailsLink": true,
    "ShowS1CheckDetailsLink": false,
    "ShowWireDetailsLink": false,
    "ShowDepositsLink": false,
    "OverlaySubtitle":
      "MTLS - MATERIALISE NV FSPONSORED ADR 1 ADR REPS 1 ORD SHS",
    "AccruedInterest": "0.00",
    "PrimeBroker": null,
    "Commission": "0.00",
    "CusipId": "57667T100",
    "ExchProcFee": null,
    "OrderHandlingFee": null,
    "Other": "0.00",
    "Principal": "-$400.00",
    "RedemptionFee": "0.00",
    "SecurityNumber": "2554803",
    "SettleDate": "06/21/2020",
    "StateTaxes": "0.00",
    "Total": "-$400.00",
    "TradeDate": "05/15/2020",
    "WithHoldingTaxes": "0.00",
    "TranPrimeBrkrAm": "0.00",
    "RowIndex": 1,
    "SourceCode": "",
    "AccountNumber": "1234",
    "CheckNumber": "",
    "CheckDate": null,
    "DepositSeqId": "0",
    "AmountVerify": null,
  }, {
    "Action": "Wire Funds Received",
    "Amount": "$5,200.30",
    "Description": "FOREIGN CURRENCY DEPOSIT",
    "FeesAndCommission": "",
    "Price": "",
    "Quantity": "",
    "Symbol": null,
    "PresentationSymbol": null,
    "TransactionDate": "03/18/2020",
    "EffectiveDate": "03/18/2020",
    "IsCharitableGiving": false,
    "ShowDetailsLink": false,
    "ShowS1CheckDetailsLink": false,
    "ShowWireDetailsLink": true,
    "ShowDepositsLink": false,
    "OverlaySubtitle": " - FOREIGN CURRENCY DEPOSIT",
    "AccruedInterest": null,
    "PrimeBroker": null,
    "Commission": null,
    "CusipId": null,
    "ExchProcFee": null,
    "OrderHandlingFee": null,
    "Other": null,
    "Principal": null,
    "RedemptionFee": null,
    "SecurityNumber": null,
    "SettleDate": null,
    "StateTaxes": null,
    "Total": null,
    "TradeDate": null,
    "WithHoldingTaxes": null,
    "TranPrimeBrkrAm": null,
    "RowIndex": 2,
    "SourceCode": "DPWRF",
    "AccountNumber": "1234",
    "CheckNumber": "",
    "CheckDate": null,
    "DepositSeqId": "23456",
    "AmountVerify": null,
  }],
  "BrokerageHistoryIn": {
    "IsAccountTypeEAC": false,
    "SortSequence": 1,
    "SortValue": 0,
    "TransactionFilters": [
      14,
      9,
      10,
      6,
      7,
      0,
      2,
      11,
      8,
      3,
      15,
      5,
      13,
      4,
      12,
      1,
    ],
    "TimeFrame": 7,
    "FilterSymbol": "",
    "FromDate": "2017-08-24T09:19:13.9362484-04:00",
    "ToDate": "2020-08-24T09:19:13.9362484-04:00",
    "ExportError": "",
    "InvalidFromDate": "",
    "InvalidToDate": "",
    "SymbolExportValue": "",
    "IncludeOptions": null,
    "DisplayTotal": false,
  },
  "TransactionTypes": {
    "Adjustments": "Adjustments",
    "AtmActivity": "AtmActivity",
    "BillPay": "BillPay",
    "Checks": "Checks",
    "CorporateActions": "CorporateActions",
    "Deposits": "Deposits",
    "Dividends": "Dividends",
    "ElectronicTransfers": "ElectronicTransfers",
    "Fees": "Fees",
    "Interest": "Interest",
    "Misc": "Misc",
    "SecurityTransfers": "SecurityTransfers",
    "Taxes": "Taxes",
    "Trades": "Trades",
    "VisaDebitCard": "VisaDebitCard",
    "Withdrawals": "Withdrawals",
  },
};
